---
title: "Mind the gap and the map: Measuing distributional and spatial polarization"
format:  
  clean-revealjs:
    slide-number: false
html-math-method:
  method: mathjax
  url: "https://ccdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Sergio J. Rey
    orcid: 0000-0001-5857-9762
    email: sey@sdsu.edu
    affiliations: 
      - Center for Open Geographical Science
      - Department of Geography
      - San Diego State University
date: last-modified
--- 

## Getis-Ord

<!------------->
<!-- homage  -->
<!------------->

::: {.notes}
Pay homage to them here
:::
---

## Overview

- Polarization
- Framework
- Empirical Illustration
- Conclusion

::: {.notes}
provide overview here
:::

---

# Polarization
::: {.notes}
Motivate the focus on polarization
:::
something

```{python}

````
something


## Polarization
what it is
End of file during parsingSymbol’s value as variable is void: {{python}}End of file during parsing
:::{.notes}
explain polarizatin
:::
End of file during parsingSymbol’s value as variable is void: {python}End of file during parsing
## Importance
:::{.notes}
Why is it important
:::
## Wolfson
End of file during parsingSymbol’s value as variable is void: {.bash}End of file during parsing

End of file during parsingSymbol’s value as variable is void: {python}End of file during parsing

## Esteban-Ray

## Geographical Polarization

## Integration

# Framework

## Graphs


## Intersection

## Components

# Empirical Illustration

## Mexico

## Trends

## More

# Conclusion

## Thanks
