name: Render and Deploy Quarto Presentation

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if needed

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render presentation
        run: quarto render wrsa25.qmd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:./  # Adjust if your output is in a subdirectory